/**
 * @file Codemode execution environment for running TypeScript/JavaScript code with native tools.
 *
 * This module provides a secure execution environment that allows running user-provided
 * TypeScript/JavaScript code with access to native TypeScript tools, algorithms,
 * Playwright automation, and other development utilities. It includes git hook management
 * and environment isolation to prevent interference with the development workflow.
 *
 * @author Generated by Reynard AI Tool-Calling System
 */

import { setupCodemodeEnvironment, buildToolsFacade, loadPlaywrightPackages, executeUserCode } from "./execution-utils";
import { setupSSHProxy, cleanupSSHProxy } from "./ssh-proxy";

export type CodeModeConfig = {
  projectRoot: string;
  timeoutMs?: number;
  sshProxy?: {
    host: string;
    port?: number;
    user?: string;
    localPort?: number;
  };
};

/**
 * Creates a CodeMode execution environment with access to native TypeScript tools, algorithms, and Playwright modules.
 *
 * @param {CodeModeConfig} config - Configuration object containing project root and optional timeout
 * @returns {Promise<CodeModeSandbox>} Promise that resolves to a CodeMode sandbox with execution capabilities
 * @example
 * ```typescript
 * const cm = await codemode({ projectRoot: "/path/to/project", timeoutMs: 10000 });
 * const result = await cm.executeCode('console.log("Hello from CodeMode!");');
 * ```
 */
export async function codemode(config: CodeModeConfig) {
  setupCodemodeEnvironment();

  // Set up SSH proxy if configured
  let proxyUrl: string | null = null;
  if (config.sshProxy) {
    try {
      proxyUrl = await setupSSHProxy(config.sshProxy);
    } catch (error) {
      console.warn("⚠️  SSH proxy setup failed:", (error as Error).message);
      console.warn("   Continuing without proxy - some network operations may fail");
    }
  }

  // Build native TypeScript tools facade for CodeMode execution
  const tools = await buildToolsFacade();

  // Load algorithms package with error handling for ES module compatibility
  let algorithms: Record<string, unknown> = {};
  try {
    algorithms = (await import("@entropy-tamer/reynard-algorithms")) as Record<string, unknown>;
  } catch (error) {
    console.warn("⚠️  Algorithms package failed to load:", (error as Error).message);
    console.warn("   Continuing without algorithms - some features may be unavailable");
    // Continue with empty algorithms object
  }

  const playwrightPackages = await loadPlaywrightPackages();
  const devToolsPackages: Record<string, unknown> = {};

  console.log("✅ Native tools system initialized with conditional execution support");

  const context = { tools, algorithms, playwrightPackages, devToolsPackages, proxyUrl };

  return {
    async healthCheck() {
      try {
        const { getAllTools } = await import("../tools");
        const tools = await getAllTools();
        return { ok: true, count: tools.length };
      } catch (e) {
        return { ok: false, error: (e as Error).message };
      }
    },
    async executeCode(code: string) {
      return executeUserCode(code, context);
    },
    async cleanup() {
      // Clean up SSH proxy if it was set up
      if (config.sshProxy) {
        await cleanupSSHProxy();
      }
    },
  };
}
